### ISSUE TITLE
EECS 452

### ISSUE THREAD

**Issue by nuggehal** [vidalborromeo/eecshelp-queue#8]
Hi,

My name is Sudheer Nuggehalli and I am currently a GSI for EECS 452. I would like to make a request to add EECS 452 to the EECS Help site to aid with my class.

Thanks,
Sudheer Nuggehalli

**Comment by vidalborromeo** [comment]
Hello Sudheer,
   Absolutely!
Can you leave me your unique name here. I'll add EECS 452, and give you
moderator access so you can add your fellow staffers.

Cheers,
    Vidal

On Jan 6, 2017 2:11 PM, "nuggehal" <notifications@github.com> wrote:

Hi,

My name is Sudheer Nuggehalli and I am currently a GSI for EECS 452. I
would like to make a request to add EECS 452 to the EECS Help site to aid
with my class.

Thanks,
Sudheer Nuggehalli

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vidalborromeo/eecshelp-queue/issues/8>, or mute the
thread

**Comment by vidalborromeo** [comment]
UPDATE:
Hi Sudheer,
    EECS 452 is available now on [eecshelp.appspot.com](eecshelp.appspot.com) (a.k.a. [eecshelp.com](eecshelp.com)). Your "@umich.edu" account has moderator-access to EECS 452. I also sent you an email with some details you can share with your fellow staffers.

You can see the full list of new (staff-requested!) features here:
[https://eecshelp.appspot.com/main#roadmap](https://eecshelp.appspot.com/main#roadmap)
[https://eecshelp-hrd.appspot.com/main#mission](https://eecshelp-hrd.appspot.com/main#mission)
